Repository atoma-network/atoma-infer, pull requests merged in 2024-08, with the labels that each got.

#36 fix: kv cache allocation
  .gitignore
  src/models/llama.rs
Labels: testing

#34 test: reshape and cache tests
  Cargo.toml
  csrc/src/cache_manager.rs
  csrc/src/lib.rs
  csrc/tests/cache_manager_tests.rs
  src/flash_attention.rs
  src/lib.rs
  src/models/llama.rs
Labels: paged-attention, testing

#35 fix: fix the shape of kv cache
  src/flash_attention.rs
Labels: bug

#42 fix: `FlashAttentionMetadata` constructor
  src/flash_attention.rs
Labels: bug

#39 tests: add tests for continuous batching llama inference
  Cargo.toml
  csrc/src/lib.rs
  csrc/tests/flash_attn_tests.rs
  src/flash_attention.rs
  src/models/llama.rs
Labels: llama, paged-attention, candle, flash-attention2

#28 feat: implement llama models with flash attention
  .gitignore
  Cargo.toml
  csrc/build.rs
  csrc/src/lib.rs
  csrc/tests/cache_manager_tests.rs
  csrc/tests/flash_attn_tests.rs
  src/flash_attention.rs
  src/models/llama.rs
Labels: llama, paged-attention, cuda, candle, flash-attention2, models

#49 test: longer generation llama tests
  Cargo.toml
  csrc/src/cache_manager.rs
  src/models/llama.rs
Labels: testing
